- project:
    templates:
      - openstack-cover-jobs
      - openstack-python3-yoga-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - lib-forward-testing-python3
      - release-notes-jobs-python3
